from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer
)


def add_heading(title, styles, story):
    story.append(
        Paragraph(f"<b>{title}</b>", styles["Heading2"])
    )
    story.append(Spacer(1, 8))


def add_list(items, styles, story, symbol="•"):
    """Add a bullet list to the PDF."""

    if not items:
        story.append(
            Paragraph("None", styles["BodyText"])
        )
        story.append(Spacer(1, 10))
        return

    for item in sorted(items):
        story.append(
            Paragraph(
                f"{symbol} {item.title()}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 12))


def generate_report(
    filename,
    score,
    job_keywords,
    resume_keywords,
    found,
    missing,
    suggestions
):

    styles = getSampleStyleSheet()
    story = []

    doc = SimpleDocTemplate(filename)

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    story.append(
        Paragraph(
            "<b><font size=20>"
            "Resume Keyword Analyzer Report"
            "</font></b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"Generated on: {datetime.now():%d %B %Y, %I:%M %p}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # --------------------------------------------------
    # ATS Score
    # --------------------------------------------------

    add_heading("ATS Match Score", styles, story)

    story.append(
        Paragraph(
            f"<font size=18><b>{score}%</b></font>",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 18))

    # --------------------------------------------------
    # Summary
    # --------------------------------------------------

    add_heading("Summary", styles, story)

    summary = [
        f"Total Required Skills : {len(job_keywords)}",
        f"Matched Skills : {len(found)}",
        f"Missing Skills : {len(missing)}"
    ]

    for line in summary:
        story.append(
            Paragraph(line, styles["BodyText"])
        )

    story.append(Spacer(1, 18))

    # --------------------------------------------------
    # Skills
    # --------------------------------------------------

    sections = [
        ("Skills Required in Job Description", job_keywords, "•"),
        ("Skills Detected in Resume", resume_keywords, "•"),
        ("Matched Skills", found, "✓"),
        ("Missing Skills", missing, "✗")
    ]

    for title, items, symbol in sections:
        add_heading(title, styles, story)
        add_list(items, styles, story, symbol)

    # --------------------------------------------------
    # Suggestions
    # --------------------------------------------------

    add_heading("Suggestions", styles, story)

    for suggestion in suggestions:
        story.append(
            Paragraph(
                f"• {suggestion}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------

    story.append(
        Paragraph(
            "<font size=10 color='grey'>"
            "Generated by Resume Keyword Analyzer"
            "</font>",
            styles["BodyText"]
        )
    )

    doc.build(story)